services:
  user:
   # builds image from Dockerfile and tags as user:1.0.0
   build: ./user
   image: user:1.0.0
   container_name: user
   depends_on:
     - redis
     - mongodb
  
  mongodb:
   build: ./Mongodb
   image: mongodb:1.0.0
   container_name: mongodb

  redis:
   image: redis:7.0   #pull redis:7 vesrion from dockerhub
   container_name: redis


  frontend:
   build: ./frontend
   image: frontend:1.0.0
   container_name: frontend
   ports:
     - "80:80"    #host:container
   depends_on:
     - user


networks:
 default:
  driver: bridge
  name: roboshop
