services:
  user:
   # builds image from Dockerfile and tags as user:1.0.0
   build: ./user
   image: user:1.0.0
   container_name: user
   depends_on:
     - redis
     - mongodb
  

  mongodb:
   build: ./Mongodb
   image: mongodb:1.0.0
   container_name: mongodb

  redis:
   image: redis:7.0   #pull redis:7 vesrion from dockerhub
   container_name: redis
  
  cart:
   # builds image from Dockerfile and tags as user:1.0.0
   build: ./cart
   image: cart:1.0.0
   container_name: cart
   depends_on:
     - redis
     - catalogue
  
  catalogue:
   build: ./catalogue
   image: catalogue:1.0.0
   container_name: catalogue
   depends_on:
     - mongodb
  
  shipping:
   build: ./shipping   #maven for java
   image: shipping:1.0.0
   container_name: shipping
   depends_on:
     - mysql
     - cart

  mysql:
   build: ./mysql
   image: mysql:1.0.0
   container_name: mysql
  
  payment:
   build: ./payment
   image: payment:1.0.0
   container_name: payment
   environment:
     CART_HOST: "cart"
     CART_PORT: "8080"
     USER_HOST: "user"
     USER_PORT: "8080"
     AMQP_HOST: "rabbitmq"
     AMQP_USER: "roboshop"
     AMQP_PASS: "roboshop123"
   depends_on:
     - rabbitmq
     - cart
     - user
  
  rabbitmq:
   image: rabbitmq:3
   environment:
    RABBITMQ_DEFAULT_USER: roboshop
    RABBITMQ_DEFAULT_PASS: roboshop123
   container_name: rabbitmq
  

    
  frontend:
   build: ./frontend
   image: frontend:1.0.0
   container_name: frontend
   ports:
     - "80:80"    #host:container
   depends_on:
     - user
     - catalogue
     - cart
     - shipping
     - payment


networks:
 default:
  driver: bridge
  name: roboshop
